# Generated by Django 5.0.4 on 2024-05-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='category',
            field=models.IntegerField(choices=[(1, 'Pre-School'), (2, 'Primary'), (3, 'Junior'), (4, 'Senior')], verbose_name='Category'),
        ),
    ]
