# Generated by Django 5.0.4 on 2024-04-30 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Post heading')),
                ('img', models.ImageField(upload_to='', verbose_name='insert image')),
                ('content', models.TextField(verbose_name='Add post content')),
                ('url', models.URLField(verbose_name='reference external links')),
            ],
        ),
    ]
