# Generated by Django 5.0.4 on 2024-05-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Post heading')),
                ('img', models.ImageField(upload_to='media/images/', verbose_name='insert image')),
                ('content', models.TextField(verbose_name='Add post content')),
                ('url', models.URLField(blank=True, verbose_name='reference external links')),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('published', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'School Post',
                'verbose_name_plural': 'School Posts',
            },
        ),
        migrations.CreateModel(
            name='UpdateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media/images/', verbose_name='Select image')),
                ('img_tag', models.CharField(max_length=60, verbose_name='Image description')),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('published', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Homepage Image',
                'verbose_name_plural': 'Homepage Images',
            },
        ),
    ]
