# Generated by Django 5.0.4 on 2024-05-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(upload_to='images/', verbose_name='insert image'),
        ),
        migrations.AlterField(
            model_name='updateimage',
            name='img',
            field=models.ImageField(upload_to='images/', verbose_name='Select image'),
        ),
    ]
