# Generated by Django 5.0.4 on 2024-05-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='updateimage',
            name='img_use',
            field=models.CharField(choices=[(1, 'gallery'), (2, 'homepage'), (3, 'all')], default=3, verbose_name='Page image assignment'),
        ),
    ]
