# Generated by Django 5.0.4 on 2024-05-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_updateimage_img_use'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='updateimage',
            options={'verbose_name': 'School Image', 'verbose_name_plural': 'School Images'},
        ),
        migrations.AlterField(
            model_name='updateimage',
            name='img_use',
            field=models.CharField(choices=[(1, 'gallery'), (2, 'homepage'), (3, 'all')], verbose_name='Page image assignment'),
        ),
    ]
