# Generated by Django 5.0.4 on 2024-05-04 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_updateimage_options_alter_updateimage_img_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateimage',
            name='img_use',
            field=models.IntegerField(choices=[(1, 'gallery'), (2, 'homepage'), (3, 'all')], default=3, verbose_name='Page image assignment'),
        ),
    ]
