# Generated by Django 5.0.4 on 2024-05-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_alter_updateimage_img_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_category',
            field=models.IntegerField(default=4, verbose_name='Post category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Insert image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(blank=True, verbose_name='Reference external links'),
        ),
    ]
